# Generated by Django 3.2.12 on 2022-04-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://p.kindpng.com/picc/s/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png', max_length=500),
        ),
    ]
