# Generated by Django 3.2.12 on 2022-04-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFood', '0003_item_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
    ]
